name: ventaslienzo
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cloud_firestore: ^4.0.5
  cupertino_icons: ^1.0.2
  firebase_core: ^2.2.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
